namespace eRestoran.WinUI.Korisnici
{
    partial class frmKlijentProfil
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmKlijentProfil));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.txtSlika = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btnOdaberi = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.chb_Status = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.btnSpremi = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPassword2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTelefon = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrezime = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtIme = new Bunifu.UI.WinForms.BunifuTextBox();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.BackColor = System.Drawing.Color.SlateBlue;
            this.groupBox1.Controls.Add(this.txtSlika);
            this.groupBox1.Controls.Add(this.pictureBox1);
            this.groupBox1.Controls.Add(this.btnOdaberi);
            this.groupBox1.Controls.Add(this.bunifuLabel1);
            this.groupBox1.Controls.Add(this.chb_Status);
            this.groupBox1.Controls.Add(this.btnSpremi);
            this.groupBox1.Controls.Add(this.txtUsername);
            this.groupBox1.Controls.Add(this.txtPassword2);
            this.groupBox1.Controls.Add(this.txtPassword);
            this.groupBox1.Controls.Add(this.txtTelefon);
            this.groupBox1.Controls.Add(this.txtPrezime);
            this.groupBox1.Controls.Add(this.txtEmail);
            this.groupBox1.Controls.Add(this.txtIme);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(583, 723);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            // 
            // txtSlika
            // 
            this.txtSlika.AcceptsReturn = false;
            this.txtSlika.AcceptsTab = false;
            this.txtSlika.AnimationSpeed = 200;
            this.txtSlika.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSlika.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSlika.BackColor = System.Drawing.Color.White;
            this.txtSlika.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSlika.BackgroundImage")));
            this.txtSlika.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSlika.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSlika.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSlika.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSlika.BorderRadius = 1;
            this.txtSlika.BorderThickness = 1;
            this.txtSlika.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSlika.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSlika.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSlika.DefaultText = "";
            this.txtSlika.FillColor = System.Drawing.Color.White;
            this.txtSlika.HideSelection = true;
            this.txtSlika.IconLeft = null;
            this.txtSlika.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSlika.IconPadding = 10;
            this.txtSlika.IconRight = null;
            this.txtSlika.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSlika.Lines = new string[0];
            this.txtSlika.Location = new System.Drawing.Point(116, 419);
            this.txtSlika.MaxLength = 32767;
            this.txtSlika.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSlika.Modified = false;
            this.txtSlika.Multiline = false;
            this.txtSlika.Name = "txtSlika";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSlika.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSlika.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSlika.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSlika.OnIdleState = stateProperties36;
            this.txtSlika.Padding = new System.Windows.Forms.Padding(3);
            this.txtSlika.PasswordChar = '\0';
            this.txtSlika.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSlika.PlaceholderText = "Telefon";
            this.txtSlika.ReadOnly = false;
            this.txtSlika.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSlika.SelectedText = "";
            this.txtSlika.SelectionLength = 0;
            this.txtSlika.SelectionStart = 0;
            this.txtSlika.ShortcutsEnabled = true;
            this.txtSlika.Size = new System.Drawing.Size(202, 41);
            this.txtSlika.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSlika.TabIndex = 17;
            this.txtSlika.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSlika.TextMarginBottom = 0;
            this.txtSlika.TextMarginLeft = 3;
            this.txtSlika.TextMarginTop = 0;
            this.txtSlika.TextPlaceholder = "Telefon";
            this.txtSlika.UseSystemPasswordChar = false;
            this.txtSlika.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Location = new System.Drawing.Point(171, 173);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(227, 219);
            this.pictureBox1.TabIndex = 16;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.WaitOnLoad = true;
            // 
            // btnOdaberi
            // 
            this.btnOdaberi.ActiveBorderThickness = 1;
            this.btnOdaberi.ActiveCornerRadius = 20;
            this.btnOdaberi.ActiveFillColor = System.Drawing.Color.SeaGreen;
            this.btnOdaberi.ActiveForecolor = System.Drawing.Color.White;
            this.btnOdaberi.ActiveLineColor = System.Drawing.Color.SeaGreen;
            this.btnOdaberi.BackColor = System.Drawing.Color.SlateBlue;
            this.btnOdaberi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOdaberi.BackgroundImage")));
            this.btnOdaberi.ButtonText = "Odaberi";
            this.btnOdaberi.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnOdaberi.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOdaberi.ForeColor = System.Drawing.Color.White;
            this.btnOdaberi.IdleBorderThickness = 1;
            this.btnOdaberi.IdleCornerRadius = 20;
            this.btnOdaberi.IdleFillColor = System.Drawing.Color.White;
            this.btnOdaberi.IdleForecolor = System.Drawing.Color.SeaGreen;
            this.btnOdaberi.IdleLineColor = System.Drawing.Color.SeaGreen;
            this.btnOdaberi.Location = new System.Drawing.Point(339, 419);
            this.btnOdaberi.Margin = new System.Windows.Forms.Padding(5);
            this.btnOdaberi.Name = "btnOdaberi";
            this.btnOdaberi.Size = new System.Drawing.Size(143, 41);
            this.btnOdaberi.TabIndex = 14;
            this.btnOdaberi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOdaberi.Click += new System.EventHandler(this.btnOdaberi_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Black", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(298, 602);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(67, 17);
            this.bunifuLabel1.TabIndex = 13;
            this.bunifuLabel1.Text = "AKTIVAN?";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chb_Status
            // 
            this.chb_Status.AllowBindingControlAnimation = true;
            this.chb_Status.AllowBindingControlColorChanges = false;
            this.chb_Status.AllowBindingControlLocation = true;
            this.chb_Status.AllowCheckBoxAnimation = false;
            this.chb_Status.AllowCheckmarkAnimation = true;
            this.chb_Status.AllowOnHoverStates = true;
            this.chb_Status.AutoCheck = true;
            this.chb_Status.BackColor = System.Drawing.Color.Transparent;
            this.chb_Status.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chb_Status.BackgroundImage")));
            this.chb_Status.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chb_Status.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chb_Status.BorderRadius = 12;
            this.chb_Status.Checked = true;
            this.chb_Status.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.chb_Status.Cursor = System.Windows.Forms.Cursors.Default;
            this.chb_Status.CustomCheckmarkImage = null;
            this.chb_Status.Location = new System.Drawing.Point(261, 598);
            this.chb_Status.MinimumSize = new System.Drawing.Size(17, 17);
            this.chb_Status.Name = "chb_Status";
            this.chb_Status.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chb_Status.OnCheck.BorderRadius = 12;
            this.chb_Status.OnCheck.BorderThickness = 2;
            this.chb_Status.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chb_Status.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chb_Status.OnCheck.CheckmarkThickness = 2;
            this.chb_Status.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chb_Status.OnDisable.BorderRadius = 12;
            this.chb_Status.OnDisable.BorderThickness = 2;
            this.chb_Status.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chb_Status.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chb_Status.OnDisable.CheckmarkThickness = 2;
            this.chb_Status.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chb_Status.OnHoverChecked.BorderRadius = 12;
            this.chb_Status.OnHoverChecked.BorderThickness = 2;
            this.chb_Status.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chb_Status.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chb_Status.OnHoverChecked.CheckmarkThickness = 2;
            this.chb_Status.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chb_Status.OnHoverUnchecked.BorderRadius = 12;
            this.chb_Status.OnHoverUnchecked.BorderThickness = 1;
            this.chb_Status.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chb_Status.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chb_Status.OnUncheck.BorderRadius = 12;
            this.chb_Status.OnUncheck.BorderThickness = 1;
            this.chb_Status.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chb_Status.Size = new System.Drawing.Size(21, 21);
            this.chb_Status.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chb_Status.TabIndex = 12;
            this.chb_Status.ThreeState = false;
            this.chb_Status.ToolTipText = null;
            // 
            // btnSpremi
            // 
            this.btnSpremi.AllowAnimations = true;
            this.btnSpremi.AllowMouseEffects = true;
            this.btnSpremi.AllowToggling = false;
            this.btnSpremi.AnimationSpeed = 200;
            this.btnSpremi.AutoGenerateColors = false;
            this.btnSpremi.AutoRoundBorders = false;
            this.btnSpremi.AutoSizeLeftIcon = true;
            this.btnSpremi.AutoSizeRightIcon = true;
            this.btnSpremi.BackColor = System.Drawing.Color.Transparent;
            this.btnSpremi.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSpremi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSpremi.BackgroundImage")));
            this.btnSpremi.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSpremi.ButtonText = "Spremi";
            this.btnSpremi.ButtonTextMarginLeft = 0;
            this.btnSpremi.ColorContrastOnClick = 45;
            this.btnSpremi.ColorContrastOnHover = 45;
            this.btnSpremi.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSpremi.CustomizableEdges = borderEdges2;
            this.btnSpremi.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSpremi.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSpremi.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSpremi.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSpremi.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSpremi.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.btnSpremi.ForeColor = System.Drawing.Color.White;
            this.btnSpremi.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSpremi.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSpremi.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSpremi.IconMarginLeft = 11;
            this.btnSpremi.IconPadding = 10;
            this.btnSpremi.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSpremi.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSpremi.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSpremi.IconSize = 25;
            this.btnSpremi.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSpremi.IdleBorderRadius = 1;
            this.btnSpremi.IdleBorderThickness = 1;
            this.btnSpremi.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSpremi.IdleIconLeftImage = null;
            this.btnSpremi.IdleIconRightImage = null;
            this.btnSpremi.IndicateFocus = false;
            this.btnSpremi.Location = new System.Drawing.Point(29, 641);
            this.btnSpremi.Name = "btnSpremi";
            this.btnSpremi.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSpremi.OnDisabledState.BorderRadius = 1;
            this.btnSpremi.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSpremi.OnDisabledState.BorderThickness = 1;
            this.btnSpremi.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSpremi.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSpremi.OnDisabledState.IconLeftImage = null;
            this.btnSpremi.OnDisabledState.IconRightImage = null;
            this.btnSpremi.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSpremi.onHoverState.BorderRadius = 1;
            this.btnSpremi.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSpremi.onHoverState.BorderThickness = 1;
            this.btnSpremi.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSpremi.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSpremi.onHoverState.IconLeftImage = null;
            this.btnSpremi.onHoverState.IconRightImage = null;
            this.btnSpremi.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSpremi.OnIdleState.BorderRadius = 1;
            this.btnSpremi.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSpremi.OnIdleState.BorderThickness = 1;
            this.btnSpremi.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSpremi.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSpremi.OnIdleState.IconLeftImage = null;
            this.btnSpremi.OnIdleState.IconRightImage = null;
            this.btnSpremi.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSpremi.OnPressedState.BorderRadius = 1;
            this.btnSpremi.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSpremi.OnPressedState.BorderThickness = 1;
            this.btnSpremi.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSpremi.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSpremi.OnPressedState.IconLeftImage = null;
            this.btnSpremi.OnPressedState.IconRightImage = null;
            this.btnSpremi.Size = new System.Drawing.Size(522, 58);
            this.btnSpremi.TabIndex = 11;
            this.btnSpremi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSpremi.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSpremi.TextMarginLeft = 0;
            this.btnSpremi.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSpremi.UseDefaultRadiusAndThickness = true;
            this.btnSpremi.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // txtUsername
            // 
            this.txtUsername.AcceptsReturn = false;
            this.txtUsername.AcceptsTab = false;
            this.txtUsername.AnimationSpeed = 200;
            this.txtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsername.BackColor = System.Drawing.Color.White;
            this.txtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsername.BackgroundImage")));
            this.txtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsername.BorderRadius = 1;
            this.txtUsername.BorderThickness = 1;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUsername.DefaultText = "";
            this.txtUsername.FillColor = System.Drawing.Color.White;
            this.txtUsername.HideSelection = true;
            this.txtUsername.IconLeft = null;
            this.txtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.IconPadding = 10;
            this.txtUsername.IconRight = null;
            this.txtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.Lines = new string[0];
            this.txtUsername.Location = new System.Drawing.Point(29, 493);
            this.txtUsername.MaxLength = 32767;
            this.txtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsername.Modified = false;
            this.txtUsername.Multiline = false;
            this.txtUsername.Name = "txtUsername";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsername.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnIdleState = stateProperties40;
            this.txtUsername.Padding = new System.Windows.Forms.Padding(3);
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUsername.PlaceholderText = "Korisničko ime";
            this.txtUsername.ReadOnly = false;
            this.txtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(522, 40);
            this.txtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsername.TabIndex = 7;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsername.TextMarginBottom = 0;
            this.txtUsername.TextMarginLeft = 3;
            this.txtUsername.TextMarginTop = 0;
            this.txtUsername.TextPlaceholder = "Korisničko ime";
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.WordWrap = true;
            // 
            // txtPassword2
            // 
            this.txtPassword2.AcceptsReturn = false;
            this.txtPassword2.AcceptsTab = false;
            this.txtPassword2.AnimationSpeed = 200;
            this.txtPassword2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword2.BackColor = System.Drawing.Color.White;
            this.txtPassword2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword2.BackgroundImage")));
            this.txtPassword2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword2.BorderRadius = 1;
            this.txtPassword2.BorderThickness = 1;
            this.txtPassword2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword2.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPassword2.DefaultText = "";
            this.txtPassword2.FillColor = System.Drawing.Color.White;
            this.txtPassword2.HideSelection = true;
            this.txtPassword2.IconLeft = null;
            this.txtPassword2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword2.IconPadding = 10;
            this.txtPassword2.IconRight = null;
            this.txtPassword2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword2.Lines = new string[0];
            this.txtPassword2.Location = new System.Drawing.Point(298, 539);
            this.txtPassword2.MaxLength = 32767;
            this.txtPassword2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword2.Modified = false;
            this.txtPassword2.Multiline = false;
            this.txtPassword2.Name = "txtPassword2";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword2.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword2.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword2.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword2.OnIdleState = stateProperties44;
            this.txtPassword2.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword2.PasswordChar = '\0';
            this.txtPassword2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword2.PlaceholderText = "Password potvrda";
            this.txtPassword2.ReadOnly = false;
            this.txtPassword2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword2.SelectedText = "";
            this.txtPassword2.SelectionLength = 0;
            this.txtPassword2.SelectionStart = 0;
            this.txtPassword2.ShortcutsEnabled = true;
            this.txtPassword2.Size = new System.Drawing.Size(253, 40);
            this.txtPassword2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword2.TabIndex = 6;
            this.txtPassword2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword2.TextMarginBottom = 0;
            this.txtPassword2.TextMarginLeft = 3;
            this.txtPassword2.TextMarginTop = 0;
            this.txtPassword2.TextPlaceholder = "Password potvrda";
            this.txtPassword2.UseSystemPasswordChar = false;
            this.txtPassword2.WordWrap = true;
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.BackColor = System.Drawing.Color.White;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 1;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = null;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 10;
            this.txtPassword.IconRight = null;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(29, 539);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties48;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword.PasswordChar = '\0';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "Password";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(253, 40);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 5;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 0;
            this.txtPassword.TextPlaceholder = "Password";
            this.txtPassword.UseSystemPasswordChar = false;
            this.txtPassword.WordWrap = true;
            // 
            // txtTelefon
            // 
            this.txtTelefon.AcceptsReturn = false;
            this.txtTelefon.AcceptsTab = false;
            this.txtTelefon.AnimationSpeed = 200;
            this.txtTelefon.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefon.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefon.BackColor = System.Drawing.Color.White;
            this.txtTelefon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefon.BackgroundImage")));
            this.txtTelefon.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefon.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefon.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefon.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefon.BorderRadius = 1;
            this.txtTelefon.BorderThickness = 1;
            this.txtTelefon.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefon.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefon.DefaultText = "";
            this.txtTelefon.FillColor = System.Drawing.Color.White;
            this.txtTelefon.HideSelection = true;
            this.txtTelefon.IconLeft = null;
            this.txtTelefon.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.IconPadding = 10;
            this.txtTelefon.IconRight = null;
            this.txtTelefon.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefon.Lines = new string[0];
            this.txtTelefon.Location = new System.Drawing.Point(298, 89);
            this.txtTelefon.MaxLength = 32767;
            this.txtTelefon.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefon.Modified = false;
            this.txtTelefon.Multiline = false;
            this.txtTelefon.Name = "txtTelefon";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefon.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefon.OnIdleState = stateProperties52;
            this.txtTelefon.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefon.PasswordChar = '\0';
            this.txtTelefon.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefon.PlaceholderText = "Telefon";
            this.txtTelefon.ReadOnly = false;
            this.txtTelefon.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefon.SelectedText = "";
            this.txtTelefon.SelectionLength = 0;
            this.txtTelefon.SelectionStart = 0;
            this.txtTelefon.ShortcutsEnabled = true;
            this.txtTelefon.Size = new System.Drawing.Size(253, 40);
            this.txtTelefon.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefon.TabIndex = 4;
            this.txtTelefon.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefon.TextMarginBottom = 0;
            this.txtTelefon.TextMarginLeft = 3;
            this.txtTelefon.TextMarginTop = 0;
            this.txtTelefon.TextPlaceholder = "Telefon";
            this.txtTelefon.UseSystemPasswordChar = false;
            this.txtTelefon.WordWrap = true;
            // 
            // txtPrezime
            // 
            this.txtPrezime.AcceptsReturn = false;
            this.txtPrezime.AcceptsTab = false;
            this.txtPrezime.AnimationSpeed = 200;
            this.txtPrezime.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrezime.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrezime.BackColor = System.Drawing.Color.White;
            this.txtPrezime.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrezime.BackgroundImage")));
            this.txtPrezime.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPrezime.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrezime.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPrezime.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrezime.BorderRadius = 1;
            this.txtPrezime.BorderThickness = 1;
            this.txtPrezime.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrezime.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrezime.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrezime.DefaultText = "";
            this.txtPrezime.FillColor = System.Drawing.Color.White;
            this.txtPrezime.HideSelection = true;
            this.txtPrezime.IconLeft = null;
            this.txtPrezime.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrezime.IconPadding = 10;
            this.txtPrezime.IconRight = null;
            this.txtPrezime.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrezime.Lines = new string[0];
            this.txtPrezime.Location = new System.Drawing.Point(298, 33);
            this.txtPrezime.MaxLength = 32767;
            this.txtPrezime.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrezime.Modified = false;
            this.txtPrezime.Multiline = false;
            this.txtPrezime.Name = "txtPrezime";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrezime.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrezime.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrezime.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrezime.OnIdleState = stateProperties56;
            this.txtPrezime.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrezime.PasswordChar = '\0';
            this.txtPrezime.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrezime.PlaceholderText = "Prezime";
            this.txtPrezime.ReadOnly = false;
            this.txtPrezime.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrezime.SelectedText = "";
            this.txtPrezime.SelectionLength = 0;
            this.txtPrezime.SelectionStart = 0;
            this.txtPrezime.ShortcutsEnabled = true;
            this.txtPrezime.Size = new System.Drawing.Size(253, 40);
            this.txtPrezime.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrezime.TabIndex = 3;
            this.txtPrezime.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrezime.TextMarginBottom = 0;
            this.txtPrezime.TextMarginLeft = 3;
            this.txtPrezime.TextMarginTop = 0;
            this.txtPrezime.TextPlaceholder = "Prezime";
            this.txtPrezime.UseSystemPasswordChar = false;
            this.txtPrezime.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.White;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(29, 89);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties60;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Email";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(253, 40);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 2;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "Email";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtIme
            // 
            this.txtIme.AcceptsReturn = false;
            this.txtIme.AcceptsTab = false;
            this.txtIme.AnimationSpeed = 200;
            this.txtIme.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtIme.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtIme.BackColor = System.Drawing.Color.White;
            this.txtIme.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtIme.BackgroundImage")));
            this.txtIme.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtIme.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtIme.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtIme.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtIme.BorderRadius = 1;
            this.txtIme.BorderThickness = 1;
            this.txtIme.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtIme.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIme.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtIme.DefaultText = "";
            this.txtIme.FillColor = System.Drawing.Color.White;
            this.txtIme.HideSelection = true;
            this.txtIme.IconLeft = null;
            this.txtIme.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIme.IconPadding = 10;
            this.txtIme.IconRight = null;
            this.txtIme.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIme.Lines = new string[0];
            this.txtIme.Location = new System.Drawing.Point(29, 33);
            this.txtIme.MaxLength = 32767;
            this.txtIme.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtIme.Modified = false;
            this.txtIme.Multiline = false;
            this.txtIme.Name = "txtIme";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIme.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtIme.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIme.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIme.OnIdleState = stateProperties64;
            this.txtIme.Padding = new System.Windows.Forms.Padding(3);
            this.txtIme.PasswordChar = '\0';
            this.txtIme.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtIme.PlaceholderText = "Ime";
            this.txtIme.ReadOnly = false;
            this.txtIme.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtIme.SelectedText = "";
            this.txtIme.SelectionLength = 0;
            this.txtIme.SelectionStart = 0;
            this.txtIme.ShortcutsEnabled = true;
            this.txtIme.Size = new System.Drawing.Size(253, 40);
            this.txtIme.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtIme.TabIndex = 0;
            this.txtIme.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtIme.TextMarginBottom = 0;
            this.txtIme.TextMarginLeft = 3;
            this.txtIme.TextMarginTop = 0;
            this.txtIme.TextPlaceholder = "Ime";
            this.txtIme.UseSystemPasswordChar = false;
            this.txtIme.WordWrap = true;
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // frmKlijentProfil
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(583, 723);
            this.Controls.Add(this.groupBox1);
            this.Name = "frmKlijentProfil";
            this.Text = "frmKlijentProfil";
            this.Load += new System.EventHandler(this.frmKlijentProfil_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtIme;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefon;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrezime;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword2;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuCheckBox chb_Status;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSpremi;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsername;
        private Bunifu.Framework.UI.BunifuThinButton2 btnOdaberi;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private Bunifu.UI.WinForms.BunifuTextBox txtSlika;
    }
}